- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: Install MySql  libraries
    ansible.builtin.pip:
      name: PyMySQL
      executable:pip3.9

  - name: Install MySql server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.basam.site
    register: mysql_info


  - name: print the output
    ansible.builtin.package:
      msg: "Msql info: {{ mysql_info }}"
